<?php

/**
 * Developer: Marco Florian (marco@marcoflorian.me)
 * Developer URI: http://www.marcoflorian.me/
 * Developer: ActiveHelper Inc.
 * Updated by :  
 * ActiveHelper Inc
 * 2015
 */
/**
 * Implements hook_init().
 */
function activehelper_livehelp_init() {
  global $base_url, $base_path;
  global $activehelper_livehelp;

  $activehelper_livehelp = array();

  $activehelper_livehelp['base_dir'] = drupal_get_path('module', 'activehelper_livehelp');
  $activehelper_livehelp['includes_dir'] = $activehelper_livehelp['base_dir'] . '/includes';
  $activehelper_livehelp['import_dir'] = $activehelper_livehelp['base_dir'] . '/server/import';
  $activehelper_livehelp['domains_dir'] = $activehelper_livehelp['base_dir'] . '/server/domains';
  $activehelper_livehelp['domains_pictures_dir'] = $activehelper_livehelp['domains_dir'] . '/%d/i18n/%s/pictures';
  $activehelper_livehelp['agents_pictures_dir'] = $activehelper_livehelp['base_dir'] . '/server/pictures/agents';
  $activehelper_livehelp['agents_pictures_dir2'] = $activehelper_livehelp['base_dir'] . '/server/agents/%d/i18n/%s';
  $activehelper_livehelp['agents_dir'] = $activehelper_livehelp['base_dir'] . '/server/agents';

  $activehelper_livehelp['includes_path'] = str_replace(DRUPAL_ROOT . '/', '', $activehelper_livehelp['includes_dir']);

  $activehelper_livehelp['server_zip'] = $activehelper_livehelp['base_dir'] . '/activehelper_livehelp_server.zip';
  $activehelper_livehelp['external_original_zip'] = $activehelper_livehelp['base_dir'] . '/activehelper_livehelp_external_original.zip';
  $activehelper_livehelp['external_zip'] = $activehelper_livehelp['base_dir'] . '/activehelper_livehelp_external.zip';
  $activehelper_livehelp['external_dir'] = $activehelper_livehelp['base_dir'] . '/activehelper_livehelp_external';

  $activehelper_livehelp['base_url'] = $base_url . str_replace('\\', '/', str_replace(DRUPAL_ROOT, '', dirname(__FILE__)));
  $activehelper_livehelp['server_url'] = $activehelper_livehelp['base_url'] . '/server';
  $activehelper_livehelp['import_url'] = $activehelper_livehelp['base_url'] . '/server/import';
  $activehelper_livehelp['domains_url'] = $activehelper_livehelp['base_url'] . '/server/domains';
  $activehelper_livehelp['domains_pictures_url'] = $activehelper_livehelp['domains_url'] . '/%d/i18n/%s/pictures';
  $activehelper_livehelp['agents_pictures_url'] = $activehelper_livehelp['base_url'] . '/server/pictures/agents';
  $activehelper_livehelp['agents_pictures_url2'] = $activehelper_livehelp['base_url'] . '/server/agents/%d/i18n/%s';
  $activehelper_livehelp['agents_url'] = $activehelper_livehelp['base_url'] . '/server/agents';
  $activehelper_livehelp['images_url'] = $activehelper_livehelp['base_url'] . '/assets/images';

  // The number of items to show per page on a listing
  $activehelper_livehelp['listing_limit'] = 10;

  $activehelper_livehelp['version'] = '3.8.0';
}

/**
 * Implements hook_menu().
 */
function activehelper_livehelp_menu() {
  $activehelper_livehelp = array();

  $activehelper_livehelp['base_dir'] = drupal_get_path('module', 'activehelper_livehelp');
  $activehelper_livehelp['includes_dir'] = $activehelper_livehelp['base_dir'] . '/includes';

  $activehelper_livehelp['includes_path'] = str_replace(DRUPAL_ROOT . '/', '', $activehelper_livehelp['includes_dir']);

  $items = array();

  $items['admin/activehelper-livehelp'] = array(
    'title' => 'Live Help Server',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'activehelper_livehelp__dashboard',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/dashboard'] = array(
    'weight' => 1,
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/domains'] = array(
    'weight' => 2,
    'title' => 'Domains',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/domains/add'] = array(
    'weight' => 1,
    'title' => 'Add domain',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains_add',
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/domains/%/%/settings'] = array(
    'weight' => 2,
    'title' => 'Settings',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains_settings',
    'page arguments' => array(3, 4),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/domains/%/edit'] = array(
    'weight' => 3,
    'title' => 'Edit',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains_edit',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/domains/%/tracking-script'] = array(
    'weight' => 4,
    'title' => 'Tracking script',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains_tracking_script',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/domains/%/download-block'] = array(
    'weight' => 5,
    'title' => 'Download block',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_domains.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__domains_download_block',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/agents'] = array(
    'weight' => 3,
    'title' => 'Agents',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_agents.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__agents',
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/agents/add'] = array(
    'weight' => 1,
    'title' => 'Add agent',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'livehelp_agents.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__agents_add',
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/agents/%/edit'] = array(
    'weight' => 2,
    'title' => 'Edit',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_agents.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__agents_edit',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/agents/%/client-info'] = array(
    'weight' => 3,
    'title' => 'Client info',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_agents.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__agents_client_info',
    'page arguments' => array(3),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/agents/%/settings/%'] = array(
    'weight' => 3,
    'title' => 'Settings',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_agents.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__agents_settings',
    'page arguments' => array(3, 5),
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats'] = array(
    'weight' => 4,
    'title' => 'Chats',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_monthly_chats.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__monthly_chats',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/monthly-chats'] = array(
    'weight' => 1,
    'title' => 'Monthly chats',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/time-by-chat'] = array(
    'weight' => 2,
    'title' => 'Time by chat',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_time_by_chat.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__time_by_chat',
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/chats/time-by-chat/%/view-messages'] = array(
    'weight' => 2,
    'title' => 'View messages',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_time_by_chat.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__time_by_chat_view',
    'page arguments' => array(4),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/chats/time-by-chat/%/email-messages'] = array(
    'weight' => 2,
    'title' => 'Email messages',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'livehelp_time_by_chat.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__time_by_chat_email',
    'page arguments' => array(4),
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/failed-chats'] = array(
    'weight' => 3,
    'title' => 'Failed chats',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_failed_chats.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__failed_chats',
    'access arguments' => array('administer site configuration')
  );
  
  $items['admin/activehelper-livehelp/chats/unanswered-chats'] = array(
    'weight' => 3,
    'title' => 'Unanswered chats',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_unanswered_chats.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__unanswered_chats',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/chats-by-department'] = array(
    'weight' => 4,
    'title' => 'Chats by department',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_chats_by_department.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__chats_by_department',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/chats-by-country'] = array(
    'weight' => 5,
    'title' => 'Chats by country',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_chats_by_country.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__chats_by_country',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/chats/chats-by-keyword'] = array(
    'weight' => 6,
    'title' => 'Chats by keyword',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_chats_by_keyword.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__chats_by_keyword',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/offline-messages'] = array(
    'weight' => 5,
    'title' => 'Offline messages',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_offline_messages.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__offline_messages',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/server-settings'] = array(
    'weight' => 6,
    'title' => 'Server settings',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_server_settings.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__server_settings',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/restricted-countries'] = array(
    'weight' => 8,
    'title' => 'Not allowed countries',
    'type' => MENU_LOCAL_TASK,
    'file' => 'livehelp_restricted_countries.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__restricted_countries',
    'access arguments' => array('administer site configuration')
  );
  $items['admin/activehelper-livehelp/restricted-countries/add'] = array(
    'weight' => 1,
    'title' => 'Add restriction',
    'type' => MENU_LOCAL_ACTION,
    'file' => 'livehelp_restricted_countries.inc',
    'file path' => $activehelper_livehelp['includes_path'],
    'page callback' => 'activehelper_livehelp__restricted_countries_add',
    'access arguments' => array('administer site configuration')
  );

  $items['admin/activehelper-livehelp/about'] = array(
    'weight' => 9,
    'title' => 'About',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'activehelper_livehelp__about',
    'access arguments' => array('administer site configuration')
  );

  return $items;
}

function activehelper_livehelp__dashboard() {
  global $activehelper_livehelp;

  drupal_add_library('system', 'drupal.collapse');

  $output = '<h2>' . t('Dashboard') . '</h2>';

  drupal_add_css('
		div.livehelp-navigation { float: left; padding: 14px 10px 6px 10px; margin-right: 4ex; text-align: center; }
		div.livehelp-navigation a { display: block; }
		div.livehelp-navigation a img { margin: 0 auto .5ex auto; display: block; }
		div.livehelp-navigation a span { display: inline-block; }
		div.livehelp-navigation a:hover, div.livehelp-navigation a:hover span { text-decoration: underline; }
		div.livehelp-left { width: 50%; float: left; }
		div.livehelp-right { width: 49%; float: right; }
	', 'inline');

  $render = '
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/domains') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/world-32.png" />
				<span>' . t('Domains') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/agents') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/user-chat-32.png" />
				<span>' . t('Agents') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/up-two-bars-32.png" />
				<span>' . t('Monthly chats') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/time-by-chat') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/clock-32.png" />
				<span>' . t('Time by chat') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/failed-chats') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/down-32.png" />
				<span>' . t('Failed chats') . '</span>
			</a>
		</div>
        <div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/unanswered-chats') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/unanswered.png" />
				<span>' . t('Unanswered chats') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/chats-by-department') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/chart-32.png" />
				<span>' . t('Chats by department') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/chats-by-country') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/chart-country-32.png" />
				<span>' . t('Chats by country') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/chats/chats-by-keyword') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/keyword.png" />
				<span>' . t('Chats by keyword') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/offline-messages') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/messages.png" />
				<span>' . t('Offline messages') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/server-settings') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/settings.png" />
				<span>' . t('Server settings') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/restricted-countries') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/restriction.png" />
				<span>' . t('Not allowed countries') . '</span>
			</a>
		</div>
		<div class="livehelp-navigation">
			<a href="' . url('admin/activehelper-livehelp/about') . '">
				<img src="' . $activehelper_livehelp['images_url'] . '/about.png" />
				<span>' . t('About') . '</span>
			</a>
		</div>
		<div style="clear: both;"></div>
	';

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Navigation'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $domains_count = db_query("SELECT COUNT( * ) FROM {livehelp_domains}")->fetchField();
  $agents_count = db_query("SELECT COUNT( * ) FROM {livehelp_users}")->fetchField();
  $departments_count = db_query("
		SELECT COUNT( * ) FROM (
			SELECT department FROM {livehelp_users} GROUP BY department
		) AS t
	")
      ->fetchField();
  $chats_count = db_query("SELECT COUNT( * ) FROM {livehelp_sessions}")->fetchField();
  $chats_today = db_query("
		SELECT COUNT( * )
		FROM {livehelp_sessions} AS ls
		WHERE DATE_FORMAT( ls.datetime, '%m/%d/%Y' ) = DATE_FORMAT( now(), '%m/%d/%Y' )
	")
      ->fetchField();
  $visitors_today = db_query("
		SELECT COUNT(*)
		FROM {livehelp_requests} AS ls
		WHERE DATE_FORMAT( ls.datetime, '%m/%d/%Y' ) = DATE_FORMAT( now(), '%m/%d/%Y' )
	")
      ->fetchField();
  $latest_aggent = db_query("
		SELECT username
		FROM {livehelp_users}
		ORDER BY refresh DESC
		LIMIT 1
	")
      ->fetchField();
  $oldest_aggent = db_query("
		SELECT username
		FROM {livehelp_users}
		ORDER BY refresh ASC
		LIMIT 1
	")
      ->fetchField();
  $fail_chats = db_query("
		SELECT COUNT( * )
		FROM {livehelp_messages} AS lm
			RIGHT JOIN {livehelp_sessions} AS ls
				ON ( ls.id = lm.session )
		WHERE lm.username IS NULL
			AND lm.message IS NULL
	")
      ->fetchField();
  $avg_chat_rating = db_query("
		SELECT IFNULL( AVG( rating ), 0 )
		FROM {livehelp_sessions}
		WHERE rating != -1
	")
      ->fetchField();
      
      
  $monthly_chats = db_query("
	            	select count(*) chats 
                    from {livehelp_sessions}
                     where `datetime` between DATE_FORMAT(CURDATE(), '%Y-%m-01') and LAST_DAY(DATE_FORMAT(CURDATE(), '%Y-%m-%d'))
	")
      ->fetchField();
      
 $last_month_chats = db_query("
                	select count(*) chats 
                    from {livehelp_sessions}
                    WHERE datetime >= DATE_FORMAT( CURRENT_DATE - INTERVAL 1 MONTH, '%Y/%m/01' ) AND 
                    datetime < DATE_FORMAT( CURRENT_DATE, '%Y/%m/01' )
	")
      ->fetchField();
      
  $last_week_chats = db_query("
                  SELECT COUNT(*) chats 
                   FROM {livehelp_sessions}
                   WHERE `datetime` >= DATE_SUB(DATE(NOW()), INTERVAL DAYOFWEEK(NOW())+6 DAY) AND `datetime` <  DATE_SUB(DATE(NOW()), 
                          INTERVAL DAYOFWEEK(NOW())-1 DAY)
	             ") ->fetchField();
          
 $current_week_chats = db_query(" 
                  SELECT  COUNT(*) chats 
                  FROM {livehelp_sessions}
                  WHERE WEEK(datetime) = WEEK(CURRENT_DATE()) AND DAYOFWEEK(datetime) IN (1,2,3,4,5,6,7) 
	             ") ->fetchField();          


 $current_week_offline_messages = db_query(" 
                  SELECT  COUNT(*) messages                   
                   FROM {livehelp_offline_messages}
                   WHERE WEEK(datetime) = WEEK(CURRENT_DATE()) AND DAYOFWEEK(datetime) IN (1,2,3,4,5,6,7)
	             ") ->fetchField();    
                 
 $last_month_offline_messages = db_query(" 
                  SELECT  COUNT(*) messages 
                    FROM {livehelp_offline_messages}
                    WHERE datetime >= DATE_FORMAT( CURRENT_DATE - INTERVAL 1 MONTH, '%Y/%m/01' ) AND 
                         datetime < DATE_FORMAT( CURRENT_DATE, '%Y/%m/01' )
	             ") ->fetchField();    
                 
  
  $weekly_failed_chats = db_query(" 
                  Select count(jls.id)        
                    from  {livehelp_sessions} AS jls
                    WHERE WEEK(jls.datetime) = WEEK(CURRENT_DATE()) AND DAYOFWEEK(jls.datetime) IN (2,3,4,5,6) and  
                    jls.active <> 0 and jls.id not in (select jlm.session  from {livehelp_messages } AS jlm   
                    where  WEEK(jlm.datetime) = WEEK(CURRENT_DATE()) AND DAYOFWEEK(jlm.datetime) IN (2,3,4,5,6))
	             ") ->fetchField();    
                 
                 
 $weekly_unanswred_chats = db_query(" 
                    Select count(jls.id)        
                      from  {livehelp_sessions} AS jls   
                        WHERE WEEK(jls.datetime) = WEEK(CURRENT_DATE()) AND DAYOFWEEK(jls.datetime) IN (2,3,4,5,6) and jls.active = 0
	             ") ->fetchField();    
                                                                   
                 
  $table_rows = array();
  $table_rows[] = array(t('Domains'), $domains_count);
  $table_rows[] = array(t('Departments'), $departments_count);
  $table_rows[] = array(t('Chats today'), $chats_today);
  $table_rows[] = array(t('Latest agent connected'), $latest_aggent);
  $table_rows[] = array(t('Failed chats'), $fail_chats);
  $table_rows[] = array(t('Monthly Chats'), $monthly_chats);
  $table_rows[] = array(t('Weekly Chats'), $current_week_chats );
  $table_rows[] = array(t('Weekly Offline Messages'), $current_week_offline_messages );
  $table_rows[] = array(t('Weekly Failed Chats'), $weekly_failed_chats );
  
  $left = theme_table(array(
    'header' => array(),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => '',
      ));

  $table_rows = array();
  $table_rows[] = array(t('Agents'), $agents_count);
  $table_rows[] = array(t('Chats'), $chats_count);
  $table_rows[] = array(t('Visitors today'), $visitors_today);
  $table_rows[] = array(t('Oldest agent connected'), $oldest_aggent);
  $table_rows[] = array(t('AVG chat rating'), $avg_chat_rating);
  $table_rows[] = array(t('Last Month Chats'), $last_month_chats);
  $table_rows[] = array(t('Last Week Chats'), $last_week_chats );
  $table_rows[] = array(t('Last Month Offline Messages'), $last_month_offline_messages );
  $table_rows[] = array(t('Weeekly Unanswred Chats'), $weekly_unanswred_chats );
  
  $right = theme_table(array(
    'header' => array(),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => '',
      ));

  $render = '
		<div class="livehelp-left">' . $left . '</div>
		<div class="livehelp-right">' . $right . '</div>
		<div style="clear: both;"></div>';

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('General stats'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $output .= '
		<div class="livehelp-left">';

  $domains_most_active_result = db_query("
		SELECT jld.name AS domain_name, COUNT( jls.id ) AS chats
		FROM {livehelp_sessions} AS jls, {livehelp_domains} AS jld
		WHERE jls.id_domain = jld.id_domain
		GROUP BY jls.id_domain
		ORDER BY 2 DESC
		LIMIT 5
	");
  $table_rows = array();
  while ($data = $domains_most_active_result->fetchObject()) {
    $table_rows[] = array($data->domain_name, $data->chats);
  }
  $render = theme_table(array(
    'header' => array(t('Domain name'), t('Chats')),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => t('No registered domains yet.'),
      ));

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Most active domains'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $agents_most_active_result = db_query("
		SELECT jlu.username AS agent_name, COUNT( jls.id ) AS chats
		FROM {livehelp_sessions} AS jls, {livehelp_users} AS jlu
		WHERE jls.id_user = jlu.id
		GROUP BY jlu.username
		ORDER BY 2 DESC
		LIMIT 5
	");
  $table_rows = array();
  while ($data = $agents_most_active_result->fetchObject()) {
    $table_rows[] = array($data->agent_name, $data->chats);
  }
  $render = theme_table(array(
    'header' => array(t('Agent name'), t('Chats')),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => t('No registered agents yet.'),
      ));

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Most active agents'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $agents_avg_rating_result = db_query("
		SELECT jlu.username AS agent_name, IFNULL( AVG( IF( jls.rating = -1, NULL, jls.rating ) ), 0 ) AS rating
		FROM {livehelp_sessions} AS jls, {livehelp_users} AS jlu
		WHERE jls.id_user = jlu.id
		GROUP BY jlu.username
		ORDER BY 2 DESC
		LIMIT 5
	");
  $table_rows = array();
  while ($data = $agents_avg_rating_result->fetchObject()) {
    $table_rows[] = array($data->agent_name, $data->rating);
  }
  $render = theme_table(array(
    'header' => array(t('Agent name'), t('Rating')),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => t('No registered agents yet.'),
      ));

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Most rated agents'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $output .= '
		</div>
		<div class="livehelp-right">';

  $visitors_most_active_result = db_query("
		SELECT CONCAT( jls.username, ' (', jls.email, ')' ) AS visitor_name_email, COUNT( jls.id ) AS chats
		FROM {livehelp_sessions} AS jls
		GROUP BY jls.email
		ORDER BY 2 DESC
		LIMIT 5
	");
  $table_rows = array();
  while ($data = $visitors_most_active_result->fetchObject()) {
    $table_rows[] = array($data->visitor_name_email, $data->chats);
  }
  $render = theme_table(array(
    'header' => array(t('Visitor name (Visitor email)'), t('Chats')),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => t('No visits yet.'),
      ));

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Most active visitors'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $agents_most_active_duration_result = db_query("
		SELECT t1.name AS agent_name, SEC_TO_TIME( SUM( TIME_TO_SEC( Time ) ) ) AS time_duration
		FROM
		(
			SELECT b.username AS name, TIMEDIFF(c.refresh, c.datetime) AS Time
			FROM {livehelp_users} AS b, {livehelp_sessions} AS c
			WHERE c.id_user = b.id
				AND DATE_FORMAT(c.datetime,'%Y%m%d') >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)
				AND DATE_FORMAT(c.datetime,'%Y%m%d') <= CURDATE()
			GROUP BY c.id
			ORDER BY CONCAT(b.firstname, ' ', b.lastname)
		) AS t1
		GROUP BY t1.name
		ORDER BY 2 DESC
		LIMIT 5
	");
  $table_rows = array();
  while ($data = $agents_most_active_duration_result->fetchObject()) {
    $table_rows[] = array($data->agent_name, $data->time_duration);
  }
  $render = theme_table(array(
    'header' => array(t('Agent name'), t('Time duration')),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => t('No registered agents yet.'),
      ));

  $render = array(
    'livehelp_navigation' => array(
      '#type' => 'fieldset',
      '#title' => t('Most active agents by time duration'),
      '#collapsed' => FALSE,
      '#collapsible' => TRUE,
      '#value' => $render,
      '#attributes' => array(
        'class' => array('collapsible')
      ),
    )
  );
  $output .= drupal_render($render);

  $output .= '
		</div>
		<div style="clear: both;"></div>';

  return $output;
}

function activehelper_livehelp__about() {
  global $activehelper_livehelp;

  $output = '<h2>' . t('About') . '</h2>';

  $table_rows = array();
  $table_rows[] = array(t('Name'), t('LiveHelp system for Drupal'));
  $table_rows[] = array(t('Version'), $activehelper_livehelp['version']);
  $table_rows[] = array(t('Check for updates'), t('<a target="_blank" href="http://www.activehelper.com/extensions/drupal-live-chat.html">http://www.activehelper.com</a>'));
  $table_rows[] = array(t('FAQ'), t('<a target="_blank" href="http://www.activehelper.com/faq.html">http://www.activehelper.com/faq.html</a>'));
  $table_rows[] = array(t('Forum'), t('<a target="_blank" href="http://www.activehelper.com/forum/drupal-extension">http://www.activehelper.com/forum/drupal-extension</a>'));
  $table_rows[] = array(t('Twitter'), t('<a target="_blank" href="https://twitter.com/activehelper">https://twitter.com/activehelper</a>'));
  $table_rows[] = array(t('FaceBook'), t('<a target="_blank" href="https://www.facebook.com/activehelpersystem">https://www.facebook.com/activehelpersystem</a>'));
  $table_rows[] = array(t('License'), t('GNU/GPL v2 - <a target="_blank" href="http://www.activehelper.com/license.txt">http://www.activehelper.com/license.txt</a>'));
  $table_rows[] = array(t('Copyright'), t('Copyright © 2010 - @year. ActiveHelper - 2014 - @year - All rights reserved', array('@year' => date('Y'))));
  $output .= theme_table(array(
    'header' => array(),
    'rows' => $table_rows,
    'attributes' => array('width' => '100%'),
    'sticky' => TRUE,
    'caption' => '',
    'colgroups' => array(),
    'empty' => '',
      ));

  return $output;
}

/**
 * A helper function that returns the file variable in a friendly format.
 * 
 * @param array $files
 * @param bool $top Optional
 * @return array 
 */
function activehelper_livehelp__helper_multiple_files($files, $top = TRUE) {
  $new_files = array();

  foreach ($files as $name => $file) {
    if ($top) {
      $sub_name = $file['name'];
    }
    else {
      $sub_name = $name;
    }

    if (is_array($sub_name)) {
      foreach (array_keys($sub_name) as $key) {
        $new_files[$name][$key] = array(
          'name' => $file['name'][$key],
          'type' => $file['type'][$key],
          'tmp_name' => $file['tmp_name'][$key],
          'error' => $file['error'][$key],
          'size' => $file['size'][$key],
        );
        $new_files[$name] = activehelper_livehelp__helper_multiple_files($new_files[$name], FALSE);
      }
    }
    else {
      $new_files[$name] = $file;
    }
  }

  return $new_files;
}

/**
 * Implements hook_block_info().
 */
function activehelper_livehelp_block_info() {
  $blocks = array();

  $blocks['block'] = array(
    'info' => t('ActiveHelper LiveHelp'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'status' => 0,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function activehelper_livehelp_block_configure($delta = '') {
  global $base_url, $base_path;
  $form = array();

  if ($delta == 'block') {
    // Get the current domain
    $query = db_select('livehelp_domains', 'd')
        ->fields('d', array('id_domain', 'name', 'status'));
    $result = $query->execute();

    $base_url = $base_url;
    $domain_name = parse_url($base_url);
    $domain_name = $domain_name['host'];
    $domain_id = 0;

    while ($data = $result->fetchObject()) {
      if (strstr($base_url, '//' . $data->name)) {
        $domain_id = $data->id_domain;
      }
    }

    $query = db_select('livehelp_users', 'u')
        ->fields('u', array('id', 'username'));
    $result = $query->execute();

    $agents_select = array();
    while ($data = $result->fetchObject()) {
      $agents_select[$data->id] = $data->username;
    }

    // To easily get the text of a language by code. We'll need this later.
    $languages_texts = array(
      'en' => t('English'),
      'sp' => t('Spanish'),
      'de' => t('Deutsch'),
      'pt' => t('Portuguese'),
      'it' => t('Italian'),
      'fr' => t('French'),
      'cz' => t('Czech'),
      'se' => t('Swedish'),
      'no' => t('Norwegian'),
      'tr' => t('Turkey'),
      'gr' => t('Greek'),
      'he' => t('Hebrew'),
      'fa' => t('Farsi'),
      'sr' => t('Serbian'),
      'ru' => t('Rusian'),
      'hu' => t('Hungarian'),
      'zh' => t('Traditional Chinese'),
      'ar' => t('Arab'),
      'nl' => t('Dutch'),
      'fi' => t('Finnish'),
      'dk' => t('Danish'),
      'pl' => t('Polish'),
      'cn' => t('Simplified Chinese'),
      'bg' => t('Bulgarian'),
      'sk' => t('Slovak'),
      'cr' => t('Croatian'),
      'id' => t('Indonesian'),
      'lt' => t('Lithuanian'),
      'ro' => t('Romanian'),
      'sl' => t('Slovenian'),
      'et' => t('Estonian'),  
      'lv' => t('Latvian'),  
      'ge' => t('Georgian')                  
    );

    // Basic options
    $options_status = array(
      '1' => t('Enabled'),
      '0' => t('Disabled')
    );
    
    // Footer Positions
		$options_footer = array(
            'None'    => t( 'None' ),
			'Right'   => t( 'Right' ),
			'center'  => t( 'Center' ),
            'Left'    => t( 'Left' )                                 
		);
        
 // Footer Positions
		$options_positions = array(
            'None'    => t( 'None' ),
			'bottom'  => t( 'Bottom' ),
			'Center'  => t( 'Center' ),
            'top'     => t( 'Top' )                                 
		);
        

    $form['block_domain_name'] = array(
      '#attributes' => array(
        'readonly' => 'readonly',
        'class' => empty($domain_id) ? array('error') : array(),
      ),
      '#title' => t('Domain name'),
      '#description' => empty($domain_id) ? '<span style="color: red; font-weight: bold;">' . t('You must register the domain @domain in order to use this block.', array('@domain' => $domain_name)) . '</span>' : '',
      '#type' => 'textfield',
      '#size' => 30,
      '#default_value' => $domain_name,
    );
    $form['block_domain_id'] = array(
      '#type' => 'hidden',
      '#default_value' => $domain_id,
    );
    $form['block_language'] = array(
      '#type' => 'select',
      '#title' => t('Domain language'),
      '#options' => $languages_texts,
      '#default_value' => variable_get('activehelper_livehelp_block_language', 'en'),
      '#description' => t('Select the language you would like to use in the status images.'),
    );
    $form['block_status_indicator_type'] = array(
      '#type' => 'select',
      '#title' => t('Status Indicator Type'),
      '#options' => array(0 => t('Domain'), 1 => t('Agent')),
      '#default_value' => variable_get('activehelper_livehelp_block_status_indicator_type', '0'),
    );
    $form['block_agent'] = array(
      '#type' => 'select',
      '#title' => t('Agent'),
      '#options' => $agents_select,
      '#default_value' => variable_get('activehelper_livehelp_block_agent', '0'),
    );
    $form['block_tracking'] = array(
      '#type' => 'radios',
      '#title' => t('Tracking'),
      '#options' => $options_status,
      '#default_value' => variable_get('activehelper_livehelp_block_tracking', '1'),
    );
    $form['block_status'] = array(
      '#type' => 'radios',
      '#title' => t('Status indicator'),
      '#options' => $options_status,
      '#default_value' => variable_get('activehelper_livehelp_block_status', '1'),
    );
    
    $form[ 'block_footer' ] = array(
			'#type' => 'select',
			'#title' => t( 'Absolute Position' ),
			'#options' => $options_footer,
			'#default_value' => variable_get( 'activehelper_livehelp_block_footer', 'None' ),
		);      
        
    $form[ 'block_positions' ] = array(
			'#type' => 'select',
			'#title' => t(''),
			'#options' => $options_positions,
			'#default_value' => variable_get( 'activehelper_livehelp_block_positions', 'None' ),
		);              
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function activehelper_livehelp_block_save($delta = '', $edit = array()) {
  if ($delta == 'block') {
    variable_set('activehelper_livehelp_block_status_indicator_type', $edit['block_status_indicator_type']);
    variable_set('activehelper_livehelp_block_agent', $edit['block_agent']);
    
    variable_set('activehelper_livehelp_block_domain_id', $edit['block_domain_id']);
    variable_set('activehelper_livehelp_block_language', $edit['block_language']);
    variable_set('activehelper_livehelp_block_tracking', $edit['block_tracking']);
    variable_set('activehelper_livehelp_block_status', $edit['block_status']);
    variable_set('activehelper_livehelp_block_footer', $edit['block_footer']);
    variable_set('activehelper_livehelp_block_positions', $edit['block_positions']);
  }
}

function activehelper_livehelp_block_view($delta = '') {
  global $activehelper_livehelp;

  $block = array();

  if ($delta == 'block') {
    $block_status_indicator_type = variable_get('activehelper_livehelp_block_status_indicator_type', '0');
    $block_agent = variable_get('activehelper_livehelp_block_agent', '0');
    
    $block_domain_id = variable_get('activehelper_livehelp_block_domain_id', '1');
    $block_language  = variable_get('activehelper_livehelp_block_language', 'en');
    $block_tracking  = variable_get('activehelper_livehelp_block_tracking', '1');
    $block_status    = variable_get('activehelper_livehelp_block_status', '1');
    $block_footer    = variable_get( 'activehelper_livehelp_block_footer', 'None' );
    $block_positions = variable_get( 'activehelper_livehelp_block_positions', 'None' );

     $absoulte_script =' ';
     
   if ($block_footer !='None'){         
          $absoulte_script =  '<p class="pin"><span style="font-size: 10pt;"><div style="position: fixed;' .$block_positions. ': 0px;' .$block_footer. ':0px; z-index:999999999999; display:block;">';                 
        }
        
    $block[ 'content' ] = '' .$absoulte_script.' 
			<script type="text/javascript" src="' . $activehelper_livehelp['import_url'] . '/javascript.php"></script>
			<script type="text/javascript">
				_vlDomain = ' . $block_domain_id . ';
				_vlAgent = ' . ($block_status_indicator_type ? $block_agent : 0) . ';
				_vlService = 1;
				_vlLanguage = "' . $block_language . '";
				_vlTracking = ' . $block_tracking . ';
				_vlStatus_indicator = ' . $block_status . ';
				startLivehelp();
			</script>
		';
  }

  return $block;
}

